# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AWS_ACCESS_KEY: AKIAICTLHQ5SEJRASB5Q
AWS_SECRET_KEY: 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
AWS_BUCKET: itarelkina-grammable
AWS_REGION:     "us-east-1"
SECRET_KEY: pk_test_Ere4Q1GE96VbT5cswQT1vA3700k02bBdS0
PUBLISHABLE_KEY: pk_test_Ere4Q1GE96VbT5cswQT1vA3700k02bBdS0

# heroku config:set SECRET_KEY=pk_test_Ere4Q1GE96VbT5cswQT1vA3700k02bBdS0
# heroku config:set PUBLISHABLE_KEY=pk_test_Ere4Q1GE96VbT5cswQT1vA3700k02bBdS0